/* Patches */
#include "alpha.c"
#include "boxdraw.c"
#include "opencopied.c"
#include "fixkeyboardinput.c"
#include "font2.c"
#include "keyboardselect_x.c"
#include "openurlonclick.c"
#include "rightclicktoplumb_x.c"
#include "st_embedder_x.c"
